/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ApiPublicIngestTaskRouteImport } from './routes/api/public/ingest-task'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestTaskRoute = ApiPublicIngestTaskRouteImport.update({
  id: '/api/public/ingest-task',
  path: '/api/public/ingest-task',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/digest': typeof DigestRoute
  '/groups': typeof GroupsRoute
  '/api/public/ingest-task': typeof ApiPublicIngestTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/digest': typeof DigestRoute
  '/groups': typeof GroupsRoute
  '/api/public/ingest-task': typeof ApiPublicIngestTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/digest': typeof DigestRoute
  '/groups': typeof GroupsRoute
  '/api/public/ingest-task': typeof ApiPublicIngestTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/digest' | '/groups' | '/api/public/ingest-task'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/digest' | '/groups' | '/api/public/ingest-task'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/digest'
    | '/groups'
    | '/api/public/ingest-task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DigestRoute: typeof DigestRoute
  GroupsRoute: typeof GroupsRoute
  ApiPublicIngestTaskRoute: typeof ApiPublicIngestTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-task': {
      id: '/api/public/ingest-task'
      path: '/api/public/ingest-task'
      fullPath: '/api/public/ingest-task'
      preLoaderRoute: typeof ApiPublicIngestTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DigestRoute: DigestRoute,
  GroupsRoute: GroupsRoute,
  ApiPublicIngestTaskRoute: ApiPublicIngestTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
