/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiRestartBridgeRouteImport } from './routes/api/restart-bridge'
import { Route as ApiPublicIngestTaskRouteImport } from './routes/api/public/ingest-task'
import { Route as ApiPublicNotifyJobsRouteImport } from './routes/api/public/notify-jobs'
import { Route as ApiPublicVapidKeyRouteImport } from './routes/api/public/vapid-key'
import { Route as ApiPublicWorkerGroupsRouteImport } from './routes/api/public/worker-groups'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestartBridgeRoute = ApiRestartBridgeRouteImport.update({
  id: '/api/restart-bridge',
  path: '/api/restart-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestTaskRoute = ApiPublicIngestTaskRouteImport.update({
  id: '/api/public/ingest-task',
  path: '/api/public/ingest-task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyJobsRoute = ApiPublicNotifyJobsRouteImport.update({
  id: '/api/public/notify-jobs',
  path: '/api/public/notify-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVapidKeyRoute = ApiPublicVapidKeyRouteImport.update({
  id: '/api/public/vapid-key',
  path: '/api/public/vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerGroupsRoute = ApiPublicWorkerGroupsRouteImport.update({
  id: '/api/public/worker-groups',
  path: '/api/public/worker-groups',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/digest': typeof DigestRoute
  '/groups': typeof GroupsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/api/restart-bridge': typeof ApiRestartBridgeRoute
  '/api/public/ingest-task': typeof ApiPublicIngestTaskRoute
  '/api/public/notify-jobs': typeof ApiPublicNotifyJobsRoute
  '/api/public/vapid-key': typeof ApiPublicVapidKeyRoute
  '/api/public/worker-groups': typeof ApiPublicWorkerGroupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/digest': typeof DigestRoute
  '/groups': typeof GroupsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/api/restart-bridge': typeof ApiRestartBridgeRoute
  '/api/public/ingest-task': typeof ApiPublicIngestTaskRoute
  '/api/public/notify-jobs': typeof ApiPublicNotifyJobsRoute
  '/api/public/vapid-key': typeof ApiPublicVapidKeyRoute
  '/api/public/worker-groups': typeof ApiPublicWorkerGroupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/digest': typeof DigestRoute
  '/groups': typeof GroupsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/api/restart-bridge': typeof ApiRestartBridgeRoute
  '/api/public/ingest-task': typeof ApiPublicIngestTaskRoute
  '/api/public/notify-jobs': typeof ApiPublicNotifyJobsRoute
  '/api/public/vapid-key': typeof ApiPublicVapidKeyRoute
  '/api/public/worker-groups': typeof ApiPublicWorkerGroupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/digest'
    | '/groups'
    | '/privacy'
    | '/settings'
    | '/api/restart-bridge'
    | '/api/public/ingest-task'
    | '/api/public/notify-jobs'
    | '/api/public/vapid-key'
    | '/api/public/worker-groups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/digest'
    | '/groups'
    | '/privacy'
    | '/settings'
    | '/api/restart-bridge'
    | '/api/public/ingest-task'
    | '/api/public/notify-jobs'
    | '/api/public/vapid-key'
    | '/api/public/worker-groups'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/digest'
    | '/groups'
    | '/privacy'
    | '/settings'
    | '/api/restart-bridge'
    | '/api/public/ingest-task'
    | '/api/public/notify-jobs'
    | '/api/public/vapid-key'
    | '/api/public/worker-groups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DigestRoute: typeof DigestRoute
  GroupsRoute: typeof GroupsRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  ApiRestartBridgeRoute: typeof ApiRestartBridgeRoute
  ApiPublicIngestTaskRoute: typeof ApiPublicIngestTaskRoute
  ApiPublicNotifyJobsRoute: typeof ApiPublicNotifyJobsRoute
  ApiPublicVapidKeyRoute: typeof ApiPublicVapidKeyRoute
  ApiPublicWorkerGroupsRoute: typeof ApiPublicWorkerGroupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restart-bridge': {
      id: '/api/restart-bridge'
      path: '/api/restart-bridge'
      fullPath: '/api/restart-bridge'
      preLoaderRoute: typeof ApiRestartBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-task': {
      id: '/api/public/ingest-task'
      path: '/api/public/ingest-task'
      fullPath: '/api/public/ingest-task'
      preLoaderRoute: typeof ApiPublicIngestTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-jobs': {
      id: '/api/public/notify-jobs'
      path: '/api/public/notify-jobs'
      fullPath: '/api/public/notify-jobs'
      preLoaderRoute: typeof ApiPublicNotifyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vapid-key': {
      id: '/api/public/vapid-key'
      path: '/api/public/vapid-key'
      fullPath: '/api/public/vapid-key'
      preLoaderRoute: typeof ApiPublicVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-groups': {
      id: '/api/public/worker-groups'
      path: '/api/public/worker-groups'
      fullPath: '/api/public/worker-groups'
      preLoaderRoute: typeof ApiPublicWorkerGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DigestRoute: DigestRoute,
  GroupsRoute: GroupsRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  ApiRestartBridgeRoute: ApiRestartBridgeRoute,
  ApiPublicIngestTaskRoute: ApiPublicIngestTaskRoute,
  ApiPublicNotifyJobsRoute: ApiPublicNotifyJobsRoute,
  ApiPublicVapidKeyRoute: ApiPublicVapidKeyRoute,
  ApiPublicWorkerGroupsRoute: ApiPublicWorkerGroupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
